"use client";
import { useEffect, useMemo, useState } from "react";

type Plan={id:number,date:string,title:string,place:string,type:"Activity"|"Travel"|"Food",time:string,done?:boolean};
type Expense={id:number,name:string,category:string,amount:number};
const initial:Plan[]=[
 {id:1,date:"2026-06-02",title:"Flight to NRT",place:"Tokyo",type:"Travel",time:"12:40 PM"},{id:2,date:"2026-06-03",title:"Land at Narita",place:"Narita",type:"Travel",time:"4:15 PM"},{id:3,date:"2026-06-03",title:"Mia’s grandparents’ house",place:"Meguro",type:"Travel",time:"6:30 PM"},{id:4,date:"2026-06-03",title:"Relax & get dinner",place:"Tokyo",type:"Food",time:"8:00 PM"},{id:5,date:"2026-06-04",title:"Shopping in Shibuya",place:"Shibuya",type:"Activity",time:"10:30 AM"},{id:6,date:"2026-06-04",title:"Free afternoon",place:"Tokyo",type:"Activity",time:"3:00 PM"},{id:7,date:"2026-06-06",title:"Shinkansen to Kobe",place:"Kobe",type:"Travel",time:"9:00 AM"},{id:8,date:"2026-06-07",title:"Day trip to Mie",place:"Mie",type:"Activity",time:"9:00 AM"},{id:9,date:"2026-06-08",title:"Mie → Nara → Kobe",place:"Nara",type:"Travel",time:"8:00 AM"},{id:10,date:"2026-06-09",title:"Osaka Aquarium Kaiyukan",place:"Osaka",type:"Activity",time:"10:00 AM"},{id:11,date:"2026-06-10",title:"Universal Studios Japan",place:"Osaka",type:"Activity",time:"8:00 AM"},{id:12,date:"2026-06-11",title:"Return to Tokyo",place:"Tokyo",type:"Travel",time:"11:00 AM"},{id:13,date:"2026-06-14",title:"Tokyo Disneyland",place:"Maihama",type:"Activity",time:"8:00 AM"},{id:14,date:"2026-06-15",title:"Tokyo DisneySea",place:"Maihama",type:"Activity",time:"8:00 AM"},{id:15,date:"2026-06-16",title:"Last day & souvenirs",place:"Tokyo",type:"Activity",time:"10:00 AM"},{id:16,date:"2026-06-16",title:"NRT → HNL",place:"Narita Airport",type:"Travel",time:"9:30 PM"}];
const initialExpenses:Expense[]=[{id:1,name:"Flights",category:"Transport",amount:1840},{id:2,name:"Disney tickets",category:"Activities",amount:310},{id:3,name:"JR trains",category:"Transport",amount:420},{id:4,name:"Food estimate",category:"Food",amount:650}];
const packSeed=["Passports & copies","Japan eSIM","Comfortable walking shoes","USJ tickets","Travel adapters","Medication"];
const cash=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
function get<T>(k:string,f:T):T{if(typeof window==="undefined")return f;try{return JSON.parse(localStorage.getItem(k)||"")||f}catch{return f}}

export default function Home(){
 const[tab,setTab]=useState("Overview"),[plans,setPlans]=useState(initial),[expenses,setExpenses]=useState(initialExpenses),[packing,setPacking]=useState(packSeed),[packed,setPacked]=useState<string[]>([]),[budget,setBudget]=useState(4500),[query,setQuery]=useState(""),[modal,setModal]=useState<"plan"|"expense"|null>(null),[toast,setToast]=useState(""),[ready,setReady]=useState(false);
 useEffect(()=>{setPlans(get("maiki-plans",initial));setExpenses(get("maiki-expenses",initialExpenses));setPacking(get("maiki-packing",packSeed));setPacked(get("maiki-packed",[]));setBudget(get("maiki-budget",4500));setReady(true)},[]);
 useEffect(()=>{if(ready){localStorage.setItem("maiki-plans",JSON.stringify(plans));localStorage.setItem("maiki-expenses",JSON.stringify(expenses));localStorage.setItem("maiki-packing",JSON.stringify(packing));localStorage.setItem("maiki-packed",JSON.stringify(packed));localStorage.setItem("maiki-budget",JSON.stringify(budget))}},[plans,expenses,packing,packed,budget,ready]);
 useEffect(()=>{if(toast){const x=setTimeout(()=>setToast(""),2200);return()=>clearTimeout(x)}},[toast]);
 const spent=expenses.reduce((s,e)=>s+e.amount,0),filtered=useMemo(()=>plans.filter(p=>(p.title+p.place+p.type).toLowerCase().includes(query.toLowerCase())),[plans,query]),grouped=Object.entries(filtered.reduce<Record<string,Plan[]>>((a,p)=>((a[p.date]||=[]).push(p),a),{})),cats=expenses.reduce<Record<string,number>>((a,e)=>(a[e.category]=(a[e.category]||0)+e.amount,a),{});
 function addPlan(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setPlans(v=>[...v,{id:Date.now(),date:String(f.get("date")),title:String(f.get("title")),place:String(f.get("place")),time:String(f.get("time")),type:String(f.get("type")) as Plan["type"]}].sort((a,b)=>a.date.localeCompare(b.date)));setModal(null);setToast("Plan added to your adventure ✨")}
 function addExpense(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setExpenses(v=>[...v,{id:Date.now(),name:String(f.get("name")),category:String(f.get("category")),amount:Number(f.get("amount"))}]);setModal(null);setToast("Expense saved")}
 const nav=["Overview","Itinerary","Budget","Packing"];
 return <main className="shell"><aside><div className="brand"><i>旅</i><div><b>Maiki</b><small>travel planner</small></div></div><nav>{nav.map((n,i)=><button className={tab===n?"active":""} key={n} onClick={()=>setTab(n)}><span>{["⌂","◫","¥","✓"][i]}</span>{n}</button>)}</nav><div className="trip"><small>UPCOMING TRIP</small><b>Japan Summer ’26</b><span>Jun 2 – Jun 16 · 15 days</span><p><strong>HNL</strong> ····· ✈ ····· <strong>NRT</strong></p></div><div className="profile"><i>MT</i><div><b>Maiki’s trip</b><small>Dreaming big 🌸</small></div></div></aside><section className="workspace"><header><b className="mobile-logo">旅 Maiki</b><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search places, plans, notes..."/></label><button className="heart">♡</button><button className="primary" onClick={()=>setModal("plan")}>＋ Add plan</button></header>
 {tab==="Overview"&&<div className="page"><section className="hero"><div className="hero-copy"><label>日本へ行こう · LET’S GO TO JAPAN</label><h1>Your Japan<br/><em>adventure awaits.</em></h1><p>Two unforgettable weeks through Tokyo, Kobe, Nara, Osaka, and a little Disney magic.</p><div><button className="primary" onClick={()=>setTab("Itinerary")}>View itinerary →</button><span>15 days</span><span>6 cities</span><span>{plans.length} plans</span></div></div><div className="art"><i className="sun"/><i className="fuji"/><b className="torii">⛩</b><span>JAPAN<br/>2026</span></div></section><Title over="AT A GLANCE" title="Your trip dashboard" action={<button className="soft" onClick={()=>setModal("plan")}>＋ New plan</button>}/><section className="stats"><Stat icon="✈" label="DEPARTURE" value="Jun 2, 2026" sub="12:40 PM · HNL"/><Stat icon="◉" label="TRIP LENGTH" value="15 days" sub="14 nights in Japan"/><Stat icon="¥" label="BUDGET LEFT" value={cash(Math.max(0,budget-spent))} sub={`${cash(spent)} of ${cash(budget)}`}/><Stat icon="✓" label="PACKING" value={`${packed.length} / ${packing.length}`} sub={`${Math.round(packed.length/packing.length*100)||0}% ready to go`}/></section><section className="twocol"><div className="card"><Title over="COMING UP" title="Next on the itinerary" action={<button onClick={()=>setTab("Itinerary")}>See all →</button>}/><div className="timeline">{plans.slice(0,4).map(p=><div className="next" key={p.id}><div className="date"><b>{new Date(p.date+"T12:00").getDate()}</b><small>{new Date(p.date+"T12:00").toLocaleString("en",{month:"short"})}</small></div><i className={p.type}/><div><b>{p.title}</b><small>{p.time} · {p.place}</small></div><span>{p.type}</span></div>)}</div></div><div className="card budget-mini"><Title over="TRIP BUDGET" title="Spending overview" action={<button onClick={()=>setTab("Budget")}>Details →</button>}/><div className="budget-top"><div><small>SPENT SO FAR</small><b>{cash(spent)}</b><span>of {cash(budget)}</span></div><div className="donut" style={{"--p":`${Math.min(100,spent/budget*100)}%`} as React.CSSProperties}><b>{Math.round(spent/budget*100)}%</b></div></div><Progress n={spent/budget*100}/>{Object.entries(cats).map(([c,a],i)=><div className="cat" key={c}><span><i className={`c${i}`}/>{c}</span><b>{cash(a)}</b></div>)}</div></section></div>}
 {tab==="Itinerary"&&<div className="page"><Title big over="JUNE 2 – 16, 2026" title="Japan itinerary" sub="Every stop, memory, and must-see in one happy place." action={<button className="primary" onClick={()=>setModal("plan")}>＋ Add activity</button>}/><div className="days">{grouped.map(([date,items])=><section className="day" key={date}><div className="daydate"><b>{new Date(date+"T12:00").getDate()}</b><span>{new Date(date+"T12:00").toLocaleString("en",{month:"short"})}</span><small>{new Date(date+"T12:00").toLocaleString("en",{weekday:"short"})}</small></div><div>{items.map(p=><article key={p.id}><button className={`check ${p.done?"done":""}`} onClick={()=>setPlans(v=>v.map(x=>x.id===p.id?{...x,done:!x.done}:x))}>{p.done?"✓":""}</button><div><small>{p.time}</small><h3>{p.title}</h3><p>⌖ {p.place}</p></div><span className={`pill ${p.type}`}>{p.type}</span><button className="del" onClick={()=>setPlans(v=>v.filter(x=>x.id!==p.id))}>×</button></article>)}</div></section>)}</div></div>}
 {tab==="Budget"&&<div className="page"><Title big over="MONEY, ORGANIZED" title="Trip budget" sub="Keep the fun high and the surprise charges low." action={<button className="primary" onClick={()=>setModal("expense")}>＋ Add expense</button>}/><div className="budget-grid"><section className="budget-main"><small>TOTAL TRIP BUDGET</small><label>$<input type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><Progress n={spent/budget*100}/><div>{[["Spent",cash(spent)],["Remaining",cash(budget-spent)],["Daily target",cash((budget-spent)/15)]].map(x=><p key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></p>)}</div></section><section className="card expenses"><Title over="RECENT" title="Expense tracker"/>{expenses.map(e=><div className="expense" key={e.id}><i>{e.category==="Food"?"🍜":e.category==="Transport"?"🚅":e.category==="Activities"?"🎟":"🛍"}</i><div><b>{e.name}</b><small>{e.category}</small></div><strong>{cash(e.amount)}</strong><button onClick={()=>setExpenses(v=>v.filter(x=>x.id!==e.id))}>×</button></div>)}</section></div></div>}
 {tab==="Packing"&&<div className="page"><Title big over="READY, SET, PACK" title="Packing list" sub="A tiny checklist for a very big adventure." action={<button className="primary" onClick={()=>{const x=prompt("What should we pack?");if(x)setPacking(v=>[...v,x])}}>＋ Add item</button>}/><div className="packing-grid"><section className="pack-status"><i>🧳</i><h2>{Math.round(packed.length/packing.length*100)||0}% packed</h2><p>{packing.length-packed.length} things left. You’ve got this!</p><Progress n={packed.length/packing.length*100}/></section><section className="card pack-list">{packing.map(x=><label className={packed.includes(x)?"packed":""} key={x}><input type="checkbox" checked={packed.includes(x)} onChange={()=>setPacked(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x])}/><span>{x}</span><button onClick={e=>{e.preventDefault();setPacking(v=>v.filter(y=>y!==x));setPacked(v=>v.filter(y=>y!==x))}}>×</button></label>)}</section></div></div>}
 </section>{modal&&<div className="backdrop" onMouseDown={()=>setModal(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}>×</button><small>{modal==="plan"?"A NEW MEMORY":"TRACK THE YEN"}</small><h2>{modal==="plan"?"Add to your itinerary":"Add an expense"}</h2><p>{modal==="plan"?"What should we do next?":"Keep your adventure on budget."}</p>{modal==="plan"?<form onSubmit={addPlan}><Field name="title" label="Plan name" placeholder="e.g. Ghibli Museum"/><div className="formrow"><Field name="date" label="Date" type="date" value="2026-06-12"/><Field name="time" label="Time" type="time"/></div><Field name="place" label="Place" placeholder="Tokyo"/><label>Category<select name="type"><option>Activity</option><option>Travel</option><option>Food</option></select></label><button className="primary">Add to itinerary</button></form>:<form onSubmit={addExpense}><Field name="name" label="Expense name" placeholder="e.g. Ramen dinner"/><div className="formrow"><Field name="amount" label="Amount (USD)" type="number"/><label>Category<select name="category"><option>Food</option><option>Transport</option><option>Activities</option><option>Shopping</option><option>Stay</option></select></label></div><button className="primary">Save expense</button></form>}</div></div>}{toast&&<div className="toast">✓ {toast}</div>}<nav className="mobile-nav">{nav.map((n,i)=><button className={tab===n?"active":""} key={n} onClick={()=>setTab(n)}><span>{["⌂","◫","¥","✓"][i]}</span>{n}</button>)}</nav></main>
}
function Title({over,title,sub,action,big}:{over:string,title:string,sub?:string,action?:React.ReactNode,big?:boolean}){return <div className={`title ${big?"big":""}`}><div><small>{over}</small><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>}
function Stat({icon,label,value,sub}:{icon:string,label:string,value:string,sub:string}){return <article><i>{icon}</i><div><small>{label}</small><b>{value}</b><p>{sub}</p></div></article>}
function Progress({n}:{n:number}){return <div className="progress"><i style={{width:`${Math.min(100,Math.max(0,n))}%`}}/></div>}
function Field({name,label,type="text",placeholder,value}:{name:string,label:string,type?:string,placeholder?:string,value?:string}){return <label>{label}<input name={name} type={type} placeholder={placeholder} defaultValue={value} required/></label>}
